/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Banner {
  'id' : bigint,
  'title' : string,
  'badgeText' : string,
  'createdAt' : bigint,
  'description' : string,
  'isActive' : boolean,
}
export interface ContactSubmission {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export interface CustomerProfile {
  'principal' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'googleMapsLink' : string,
  'email' : string,
  'phone' : string,
  'location' : string,
}
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'createdAt' : bigint,
  'deliveryDate' : string,
  'productId' : bigint,
  'productName' : string,
  'deliverySlot' : string,
  'email' : string,
  'notes' : string,
  'discount' : number,
  'quantity' : bigint,
  'phone' : string,
  'totalPrice' : number,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'unit' : string,
  'description' : string,
  'isActive' : boolean,
  'stock' : bigint,
  'price' : number,
}
export interface Review {
  'id' : bigint,
  'customerName' : string,
  'createdAt' : bigint,
  'productId' : bigint,
  'productName' : string,
  'comment' : string,
  'rating' : bigint,
  'customerEmail' : string,
}
export interface Stats {
  'pendingCount' : bigint,
  'cancelledCount' : bigint,
  'totalOrders' : bigint,
  'deliveredCount' : bigint,
  'totalRevenue' : number,
  'processingCount' : bigint,
  'outForDeliveryCount' : bigint,
}
export interface StoreSettings {
  'lowStockThreshold' : bigint,
  'deliveryZones' : string,
  'businessAddress' : string,
  'whatsappNumber' : string,
  'isStoreOpen' : boolean,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[string, string, number, string, bigint], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBanner' : ActorMethod<
    [string, string, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'deactivateProduct' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteBanner' : ActorMethod<[bigint], { 'ok' : null } | { 'err' : string }>,
  'exportOrdersCSV' : ActorMethod<[], string>,
  'getActiveBanners' : ActorMethod<[], Array<Banner>>,
  'getAllBanners' : ActorMethod<[], Array<Banner>>,
  'getAllCustomerProfiles' : ActorMethod<[], Array<CustomerProfile>>,
  'getAllOrders' : ActorMethod<[[] | [string]], Array<Order>>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getMyOrdersByEmail' : ActorMethod<[string], Array<Order>>,
  'getMyProfile' : ActorMethod<[], [] | [CustomerProfile]>,
  'getOrderStats' : ActorMethod<[], Stats>,
  'getProductById' : ActorMethod<[bigint], [] | [Product]>,
  'getProductReviews' : ActorMethod<[bigint], Array<Review>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getStoreSettings' : ActorMethod<[], StoreSettings>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<
    [bigint, string, string, string, bigint, string, string, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'registerCustomerProfile' : ActorMethod<
    [string, string, string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactForm' : ActorMethod<
    [string, string, string, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'submitReview' : ActorMethod<
    [bigint, string, string, string, bigint, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'updateBanner' : ActorMethod<
    [bigint, string, string, string, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateOrderStatus' : ActorMethod<
    [bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateProduct' : ActorMethod<
    [bigint, string, string, number, string, bigint, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateStoreSettings' : ActorMethod<
    [string, string, string, boolean, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];