/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'createdAt' : bigint,
  'productId' : bigint,
  'productName' : string,
  'email' : string,
  'notes' : string,
  'quantity' : bigint,
  'phone' : string,
  'totalPrice' : number,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'unit' : string,
  'description' : string,
  'isActive' : boolean,
  'stock' : bigint,
  'price' : number,
}
export interface Stats {
  'pendingCount' : bigint,
  'cancelledCount' : bigint,
  'totalOrders' : bigint,
  'deliveredCount' : bigint,
  'totalRevenue' : number,
  'processingCount' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[string, string, number, string, bigint], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deactivateProduct' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'exportOrdersCSV' : ActorMethod<[], string>,
  'getAllOrders' : ActorMethod<[[] | [string]], Array<Order>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getOrderStats' : ActorMethod<[], Stats>,
  'getProductById' : ActorMethod<[bigint], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<
    [bigint, string, string, string, bigint, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'submitContactForm' : ActorMethod<
    [string, string, string, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'updateOrderStatus' : ActorMethod<
    [bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateProduct' : ActorMethod<
    [bigint, string, string, number, string, bigint, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];